/* WARNING! All changes made to this file will be lost! */

#ifndef W_INCLUDE_CSP_AUTOCONFIG_H_WAF
#define W_INCLUDE_CSP_AUTOCONFIG_H_WAF

#define GIT_REV "v1.6-1072-g6e7f046"
#define CSP_FREERTOS 1
/* #undef CSP_POSIX */
/* #undef HAVE_SYS_SOCKET_H */
#define CSP_QFIFO_LEN 15
#define CSP_PORT_MAX_BIND 16
#define CSP_CONN_RXQUEUE_LEN 15
#define CSP_CONN_MAX 8
#define CSP_BUFFER_SIZE 256
#define CSP_BUFFER_COUNT 15
#define CSP_RDP_MAX_WINDOW 5
#define CSP_RTABLE_SIZE 10
#define CSP_REPRODUCIBLE_BUILDS 0
#define CSP_ENABLE_CSP_PRINT 1
#define CSP_PRINT_STDIO 1
#define CSP_USE_RDP 0
#define CSP_USE_HMAC 0
#define CSP_USE_PROMISC 0
#define CSP_USE_RTABLE 0

#endif /* W_INCLUDE_CSP_AUTOCONFIG_H_WAF */
